apiVersion: v1
kind: Secret
metadata:
  name: mediamanager-secret
  namespace: default
type: Opaque
stringData:
  MEDIAMANAGER_AUTH__TOKEN_SECRET: ENC[AES256_GCM,data:0PSE91so+LnIuRtegUEsUwxaZze++4oP5gI6iG7VOIpRbJDLb9XevXFqMYccrCR+hCqb8N0JwuPbF9h0sYYl7A==,iv:OtjqBkS+08tzFDUqTHHYJqGMrOFKXo5RjV7r8D7atEI=,tag:ZpzsQ/MNyQqLwFej9l0ERA==,type:str]
  MEDIAMANAGER_DATABASE__PASSWORD: ENC[AES256_GCM,data:F63d+RwgzYqRvOY5jtJzoBtqKAEKXFgDv1pGSpYmrcc=,iv:ybcVOoxtF0fzCb6Zek4oAiKkjwlb8uNq+oik5Vcw94I=,tag:OhJwo3dW9IR4Z8qe4jTRWw==,type:str]
sops:
  age:
    - recipient: age1v5nv69s859gf2494tevycyflcyezltjgvcss75ctgpdpv6wtu3fquywey3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dHZpUFFha2VjSXBUeFJC
        NCtyVDFvRVVQRjgwV2V4UlhwQTk4NkNlREN3CkZPbG5UYnE1b1JnWFdQcU9kOW42
        eEJwNG5OWGNDdzczWG9EWHBBeHNja00KLS0tIFVUTDdHaXJmSEJvTFY4aWxhY3dO
        U3lKOFZJeG5KRmI4K3FJdWRXc214c00KLmkaR2vcDhmmjaglRQAf0NHRPJBO6ZZB
        lGB1hwo8qjGuP4Nv1yZgmmVOcPO7EBGnaX4+tHuldYjGJj2oQwoR2Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-10T20:37:51Z"
  mac: ENC[AES256_GCM,data:W7w0CFAklTJft5HkewGU1uxuGHkHLEqPAtooGL1tlsw6NWBGwo8mK6EpjLiePkaNgbzyFL2VQNnuz8nUGDITTDaE4VZKGZtRWFziwneiRxghvz2Eu7ioVofep6zcp1mNv8Bns5r+qb5aQ6KU+2/2kdvMltGdeZbkwo0CdHQwY7A=,iv:M+Lo7WaQkSTpXXgDvAZtoAGHdnvY85eB5Of32LbvTMQ=,tag:19y2+1v5EcYIkQ1im+jJbQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
