apiVersion: v1
kind: Secret
metadata:
  name: mediamanager-secret
  namespace: default
type: Opaque
stringData:
  MEDIAMANAGER_AUTH__TOKEN_SECRET: ENC[AES256_GCM,data:luHuF0qtOQKZWqU3smIsE+91L63/c8Jgwa0sdLWYYlhac20HGn//ujY9DduWOcxjBOF1GsUXBluYqnuNs87lNA==,iv:OU54jEht18zSRimKQsNWT/RRzGf/mIajpMGafYlfttk=,tag:e7ShK6RN3d94ulwmST3I3g==,type:str]
  MEDIAMANAGER_DATABASE__PASSWORD: ENC[AES256_GCM,data:S1cC63MONl+E6No3knHolbsSHVSnp53vmcN34NnxXnk=,iv:fuJfwO3+z0cZ/ve54Ve/dX8C0dPNwOL6IgZBMpNB9VU=,tag:QypA5v3aWaWaX0zYJnMphQ==,type:str]
  MEDIAMANAGER_TORRENTS__QBITTORRENT__PASSWORD: ENC[AES256_GCM,data:qSfXNQHrVdw=,iv:GKd1PjDdAnUE+l4jL8pVlRiBIgjWWTybNjpbvIzBpSU=,tag:hC5Ai3T3Kz8pM9kRDTZHvQ==,type:str]
  MEDIAMANAGER_INDEXERS__PROWLARR__API_KEY: ENC[AES256_GCM,data:O8xhEpVC3JFTSh9ry6kkBj4VlHfwhOBMBdc/2aZSrog=,iv:9yl6PmVJuElwz638FUGl/RG7AJ+QN62y15uTqEOSav0=,tag:RiP63Myy95SHRgURuCFcPw==,type:str]
sops:
  age:
    - recipient: age1v5nv69s859gf2494tevycyflcyezltjgvcss75ctgpdpv6wtu3fquywey3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSll1Y1V1RnU3VUJIaVBY
        YUJWcUtXMVY3MDNmWmNQUTlWUWtqZUp1WkVRCndVQ21rNFlxYzcyQmhWQ0hZRTdL
        aGZQVE1ubFFnemZlZzRySWQxVTZMZ1kKLS0tIHdpNGd3SFVoRzRPcGh3UFJHQlVt
        SHp3SVI0MXpFMnRBN2c1VkZtQVRKY2MKABAZxudyBNZYpvSr0P4jDImu6/qzr+SH
        v1KBXqVy999n06c+wO24VPWnsycAJMk2VbREo2BusEkFVT+IHQ19VQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-10T21:15:30Z"
  mac: ENC[AES256_GCM,data:xqwm5TEDaibDL7K9Pt6RPWrYDAQdnhiegO8yrjU0EMkgyDLdlmh7QMDs9zmDHeK2WgBOfXEJ57R6GxJC2FFyQJmcYa00eO2nF3YGaSUrhL03squGAB/yLd5k83NAPNlnvXIHllcktcYgyo/wumOpID5stvrHqfNlsmSz+3FTWrY=,iv:FRymzKV+08z03YCEVsMx6YJ4Z2IgWaDF+2v3OLfVgsw=,tag:aHloe1nqDAktFd7uTBgF4g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
