---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: requestrr
spec:
  parentRefs:
    - name: envoy-internal
      namespace: network
  hostnames:
    - requestrr.ragas.cc
  rules:
    - backendRefs:
        - name: requestrr
          port: 4545
