---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: image-automation
  namespace: flux-system
spec:
  dependsOn:
    - name: flux-instance
      namespace: flux-system
  interval: 1h
  path: ./kubernetes/apps/flux-system/image-automation/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: flux-system
  wait: true
