apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:E4g1VECZcEwgADLIWknoQXhgsAxgov4XXlprZdAbBts=,iv:RcU917XiZPBMHkh1k6Pp7ZoNBjLWTbBGIL8L6x9/ezI=,tag:cdSxPBAVnLSsfQlpDapEsw==,type:str]
sops:
  age:
    - recipient: age1v5nv69s859gf2494tevycyflcyezltjgvcss75ctgpdpv6wtu3fquywey3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGamRjWXVpYmx6YU5pTFRX
        VWRXT25xYWtST1JpNHdVeVBEcFV0REVjUFRrCmFTcmtpSzNqOHM0ZDRDY0ZYcGRt
        eWtOelhTL3E2OXlHV1BVT1lUbmIzL2sKLS0tIHh5Zlo4Mjd5VUpaWjNTQzNDUnF5
        RDczRzFTcTI2U2lDTUtITGVMZVEzMlUKizXN5BFWCDKl8mmAtU39u0edCdW1+/s3
        YjeBgkTSdsY9Bju3ZPBEnYwJnvQgOznZp34kO+cKQ8O1FXtNgMBIMw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T03:16:23Z"
  mac: ENC[AES256_GCM,data:NL6I82t2iaeFDcnmwAWSnNITDpHcZyHqTlTUTuysacICaaJfxeiRcru5mTj9stvDekVrk6FtcgJ4tTE6nc48yc9p90I9eV5Lylt6+rHMFkneiUYxCXh82s+h0+iOts+X0s10ybMnqELAYymsKBqhp6W8adIzMcnglQxf/BvJ2/E=,iv:Oj+OiR8bmAkLHWdr4ZeHLp2ttFAoyiL6vI/OvS2MI74=,tag:DmJ7bl1ZugUt1E2SCdIeVw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
