apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:HMxE87gv7dgnDyFqE199/h9Vl9SlOLxb43Bh8PmrH4/4/jp7Zqb/ZQ==,iv:jgIcd18B6Kc4REftfw+LImL8yXloO9gtLffWmm4osEY=,tag:91e92EHN34XIh4+Z9F+FYw==,type:str]
sops:
  age:
    - recipient: age1v5nv69s859gf2494tevycyflcyezltjgvcss75ctgpdpv6wtu3fquywey3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZzM0UXhVTUdFMTlCZlJv
        Mmg4VDRWT3NlVXY0ZFpnTmZHWXVpRWN5dEFnCjRFWWl0MS85aTV3cUIvOFV3RnZm
        V0RzNlpvYnNzOXFJMTI2aURsTlNZRHcKLS0tIDZGRXQ5VWhoYWVxTTdCZVhvVmR5
        QXMxemZhU2pQWUxMZWVwM2YxUURyMVUKENs04yqZsd1a1jN2yyInQ19GgwysAWn3
        YcU7lFvcZiN8OQW146XtFTJRvjpPfV+lyykpP2tFpY4WemldqGT2BA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T04:42:18Z"
  mac: ENC[AES256_GCM,data:iBU1SYp4H9AlWXdpYhWqXAE+A8mjpPRacRsJ5JtoxgSqQ6GKFBHBKTYEkLzM1drJaNT2k+vhlHFqD6+R5dkJx0iovSb7WQ5V+afSV3O+SWNOXjQu8pIaLPF7IoDtJsV8qxLuEcFQudNFhuQgb4jHFVxh08vimiHthFrxxc44sCU=,iv:0RHfd4EvfRHzaO0NgCPJlkFZBMLpqHV3NzFXhKsrUgo=,tag:IUBOeds6rfOqu7o0NnCbCA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
