---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ceph-csi-rbd
spec:
  interval: 30m
  chart:
    spec:
      chart: ceph-csi-rbd
      version: 3.15.1
      sourceRef:
        kind: HelmRepository
        name: ceph-csi
        namespace: storage
  values:
    csiConfig:
      - clusterID: "eb53e78d-4b17-4e8c-8186-cd82025a8917"
        monitors:
          - "172.16.1.2:6789"
          - "172.16.1.3:6789"
          - "172.16.1.4:6789"
          - "172.16.1.5:6789"

    provisioner:
      replicaCount: 2
      provisioner:
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            memory: 512Mi
      attacher:
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            memory: 256Mi
      resizer:
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            memory: 256Mi
      snapshotter:
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            memory: 256Mi

    nodeplugin:
      plugin:
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            memory: 256Mi
      registrar:
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 128Mi

    storageClass:
      create: false

    secret:
      create: false
      name: ceph-csi-rbd-secret
