apiVersion: v1
kind: Secret
metadata:
  name: ceph-csi-rbd-secret
stringData:
  userID: ENC[AES256_GCM,data:1HtBSytEbZRUgA==,iv:w9nxPWtIx8mbpcBjAPeUaMVMLmHuytcvLRYcPogrv+I=,tag:0eiTBliJDyIOzpdzbdm9tw==,type:str]
  userKey: ENC[AES256_GCM,data:jkQoM6dBxLpGRqc0EWTKP2nulS/Gcft6/+zsWPhfMMCE+4BGJXkC1w==,iv:UvcuWvnNKtD47C5WS9iODyWwFVfJKbepGsOqBKPiN2k=,tag:AXt3ACe//PvTmZhIYLK2EA==,type:str]
sops:
  age:
    - recipient: age1v5nv69s859gf2494tevycyflcyezltjgvcss75ctgpdpv6wtu3fquywey3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETmlXMll5NWltNXJhdHpM
        WCthdURXb0pvN1pkSlZOL0FmYWVyOHp5bnpVClJFd000bm1CZk45dkdzWnpTckpx
        bUdrRm5RYmpXbnFkNEpCUTgvdVNML0kKLS0tIHZ3R0t5MnFwVGV1SWNpRktjVkF0
        YUMvWGRTZjBXYUtIL0gwd2RxMGtxUkkKLheVNKAIZ1Z3jBMgQ3CYWZvpAc4OLvxj
        j0Ja+YYSdbBy5YglTK/1TWjkyxQEMD+Gjz1SjC4BWPbfBL8nVYbbGQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T08:01:57Z"
  mac: ENC[AES256_GCM,data:/Tb8gN9feU39Xe/IXSuvF4KB4vDzVrzxxsLv9aU4/MZ0VoznL9xPCUs9i6Mvv0Lr3G5U1SQ/n9pQOFdLEN838dnL1IOWyFnCV/XHkeGAiefXnXRpHFsHq8ean/ZzhComVVPAhPKDTcUrcCgcYRaTNl5pxID6d/v3P+wKdlwOp1Q=,iv:+vIozk/qMVWgxHKwhK+VOBnGZ339bHz6rPEGFzER9xY=,tag:4BR0tdUxmcqDhyq5+u1sfQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
