apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:puEMfU4nS0U=,iv:6CnHyF/Hx1sXIAU/u90GhCEZSY1Fdh1tdjOARuQR+Rc=,tag:ktlAIYvK+xivg04CdKw5+A==,type:str]
sops:
  age:
    - recipient: age1v5nv69s859gf2494tevycyflcyezltjgvcss75ctgpdpv6wtu3fquywey3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVThLS2hDV2NmTnJ5SFZn
        cmRsclBoUmRidkpMNnMwdEtrN0FTTllJemw4CmdCZVBDUXB5T2FxaXlBNVBteUpE
        cUgyeVRSbmxselhTWDBKZTVoVTFMVzQKLS0tIG1GUFVoeUVmUmNmOWZsWGoyUUV3
        RjVOOHVwcy9qWk5nTnNWSUhvVnRUQ1UKV2ot0cQFz2HJEB+hORXr57Yf0q9aBUY3
        6xFkIoFFVNhDrFJOfKaVSYjqqGsf8gcmJQHzpOFdUYuKNmZi8I8/PA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T03:16:23Z"
  mac: ENC[AES256_GCM,data:nUoc8ZDXQxNGXzUfgpoTaQQbVyT3nEc0Pdua0QpU6gRHcO5PqxUTFWIcbVKoZOCqjAe6tW2VQwF5XouzgYjcvy7phzX5Od77KAbwhHv51dY+6P0G6dbKBZISaOAHH7xXdgTw1GBfP+ah+lLMy1HF/ZBgM4r+/7uIyorvK0CL5/g=,iv:ToZFnXJ54xcWhqAvxxE9UVuTLi+rKrY1L9thSV5lmhs=,tag:6nA2hoyrBzlJgkZ1Kte+Eg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
