apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:5op92xzjtOo=,iv:MiZT2wBOWDsqgnr2wcVKF9kzRfWmv3vRF4tOmOPothY=,tag:Ew64QVd5sYewb2H077TMpw==,type:str]
  SECRET_ACME_EMAIL: ENC[AES256_GCM,data:5f57pVsWRoXwO3ogN2CI,iv:ob8pmi0PX9j96dgk2qWXYXIXd/upXwQcMttrzikWNVQ=,tag:/z9GsgJtGXOnGCNmVbtU3A==,type:str]
sops:
  age:
    - recipient: age1v5nv69s859gf2494tevycyflcyezltjgvcss75ctgpdpv6wtu3fquywey3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WU0zMzBaU2RhZnY3WkN6
        cnF3RUdDWEp3MFdMTjEwUEJha0I3WnpNcEhVCjhQdjJvUXpVdXMrYk8vNW4wRE5Y
        YncxejdIS1pEd1l0NzJvV2g5QUJwanMKLS0tIERNL3BDdk4ya0F2ZU1WL1pjZkpv
        STdaTVl5VW9OY0FHKyt5aVg5QWNPcEEKqSQ4qGie926if+tQQ5kYmjTf8rHhEc/n
        QiWpg0GvcBp3/GrucWf64hrbpUpBgBJOQeaEKPnf9X+li3wJafYTcA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T04:41:39Z"
  mac: ENC[AES256_GCM,data:VKJ8HKVRZRc5Za64ntRDful6UnHLI7D4cuao2MvoWyWT5VzdOK3o1lCoOk97bU3lotVGWLED6LVzzvcJOD1FdUDWdFBB8imMwc9J32WoyJUgHiwoZPi/05Sl5VNgd7BwS6sIq3tDn67r0c2ZJpPdzG3doPlmwns34ScFy6gnrwo=,iv:N3VfokcBylc49/GvnoYvED3C/KKs3mSehoag4A4htPk=,tag:b5BI+PtPAFRcA83PpasCvQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
