apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:XkBXGx+g8Mp9PTUXR2ad3DGJBoSyKEE02TMVY3OYpAk=,iv:oBW3KFePEm+CSo8DP8FWHkgrgaNrvadisDQa/45RF+U=,tag:Ilt+JVK7V/0bB1lBpzodMw==,type:str]
sops:
  age:
    - recipient: age1v5nv69s859gf2494tevycyflcyezltjgvcss75ctgpdpv6wtu3fquywey3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6M09RcU5aQklxZU5zV2Y0
        cmNiS3FlZ0Ird2xSNnQ1WHJzQ3NnOVBDcEE0Ck9IMi8yZ2UwZ3BYTjhmTHpRenY5
        SGRIaHlzd2tqSEk4T3M4YmtFT1pzRmcKLS0tIExIR3FPM3BCTXhQK2hzNTZnZHFw
        VkxoeE0rMVRGcUJtbEliUDQ1blZVQ0kKRmLo1XbNKN1iaGevgFhR/EOZeA34wzL1
        0yqcjJmV5iYavc6X8lvAST8vivLYkS6JilGQr0NlgPJwMmGKfi/+sw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T03:16:23Z"
  mac: ENC[AES256_GCM,data:Ixg17CEv0BDp3v6UCXqDW7uOj5XqYENcv29S76129pGNlKnQf6UdKT2QJjoYz2n5DkdJMX9svuOwNBNcDPu9O0CGPxnPVs0ywQdhtKn0ewTvnQRyRtabrws8wKbVp/emU4PHagdoFLS0OoIMq52iBVg0B/pmwxR1t4ucWMBcuCk=,iv:frjNJskA9/8YJ1pQlwYK5qY8C31phu8VTMIfOcHmsQ0=,tag:il9DV0LWY9UD/yvOVvmxgA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
