---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: huntarr
spec:
  parentRefs:
    - name: envoy-internal
      namespace: network
  hostnames:
    - huntarr.ragas.cc
  rules:
    - backendRefs:
        - name: huntarr
          port: 9705
