---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    app.kubernetes.io/part-of: monitoring
    pod-security.kubernetes.io/enforce: "privileged"
    pod-security.kubernetes.io/audit: "restricted"
    pod-security.kubernetes.io/warn: "restricted"
