apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ceph-csi
resources:
  - namespace.yaml
  - helmrelease.yaml
# Note: You'll need to create a secret with your Ceph credentials
# kubectl create secret generic csi-rbd-secret \
#   --namespace ceph-csi \
#   --from-literal=userID=admin \
#   --from-literal=userKey=<your-ceph-key>
