---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-maintenance
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-maintenance
rules:
  - apiGroups: [""]
    resources: ["pods", "secrets", "namespaces"]
    verbs: ["get", "list", "delete"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-maintenance
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-maintenance
subjects:
  - kind: ServiceAccount
    name: cluster-maintenance
    namespace: default
