apiVersion: v1
kind: Secret
metadata:
  name: cluster-maintenance-discord
type: Opaque
stringData:
  DISCORD_WEBHOOK: ENC[AES256_GCM,data:Z/r+7IcTkiGYHtoviAnuowsoIFT0Aw6X5UvhLr4JN9BDGq+Iaz6k9Z5e1erczDVMLucS7LyORoR2a5j+dOOmvvViJhbx1Q9IHJzqXXyY3xYr60GAy00KEaYKiVsGyeg8ljDfeZveh1jAdpVqWeV1xB6/vOPiBFMbYw==,iv:ezfi5Z8JgCIeqWWTzhsLQ4ufmfiQtL5P4TJ1pl7jKc4=,tag:HdDs0xBlwt9YAoh6mKyIGw==,type:str]
sops:
  age:
    - recipient: age1v5nv69s859gf2494tevycyflcyezltjgvcss75ctgpdpv6wtu3fquywey3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0KzBmcjlvT2dsUHVwRXN6
        MmNGaWVwYWVLSzZJVTd1UXZGQjF1aFl3cFNvCjZWbjJHajJPbHpXaDc5elZhYnNI
        b3p6dFg2K2dMd251QkN3V2FHS2ZzUmcKLS0tIDl2RzNJTVZWaDFXQkNNQnhrMEtB
        T0RCZ3Q5MDRHMDFhL0EveU5OL0trWncKxI7V4UDh9/+mP2jqF0+b4DUZTQhwEtmN
        hsfa91lO1qtDF6oO0LvKcGLK49l2wzxYuDRdwLQoMsNx8vcezFx+/Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-02T00:30:55Z"
  mac: ENC[AES256_GCM,data:E6FZ93QQvvNakC3zDC1PpIOqAydnFfOUJgxFlvcCakPjOO6a67OOblPsFwtxfU3zv8zpy9zeKeqP3EafmqXycdzt2YRLZz4kUgV6892DTiNezQ3JFxFP6zu5nIzNSTnangHTKEV844krI1ZDnC/9ZZ0LXlLI95XFQwlOmea1fwg=,iv:W42QMw7IQIICjXNC7nqs1sVevh3CuVyLaa/q3YfhJ3M=,tag:RIqReecLfOs2+wZmFZ5Rag==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
