---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./cluster-maintenance/ks.yaml
  - ./media-storage/ks.yaml
  - ./apprise/ks.yaml
  - ./echo/ks.yaml
  - ./homepage/ks.yaml
  - ./huntarr/ks.yaml
  - ./mkdocs/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./requestrr/ks.yaml
  - ./seerr/ks.yaml
  - ./overseerr/ks.yaml
  - ./sonarr/ks.yaml
  - ./speedtest-tracker/ks.yaml
  - ./unpackerr/ks.yaml
  - ./agregarr/ks.yaml
