---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./apprise/ks.yaml
  - ./bazarr/ks.yaml
  - ./echo/ks.yaml
  - ./homepage/ks.yaml
  - ./mkdocs/ks.yaml
  - ./seerr/ks.yaml
  - ./speedtest-tracker/ks.yaml
