---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: snapshot-controller-crds
  namespace: flux-system
spec:
  targetNamespace: kube-system
  interval: 1h
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/storage/snapshot-controller/crds
  wait: true
