---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: ceph-rbd-snapclass
  labels:
    velero.io/csi-volumesnapshot-class: "true"
driver: rbd.csi.ceph.com
deletionPolicy: Delete
parameters:
  clusterID: eb53e78d-4b17-4e8c-8186-cd82025a8917
  csi.storage.k8s.io/snapshotter-secret-name: ceph-csi-rbd-secret
  csi.storage.k8s.io/snapshotter-secret-namespace: storage
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: ceph-cephfs-snapclass
  labels:
    velero.io/csi-volumesnapshot-class: "true"
driver: cephfs.csi.ceph.com
deletionPolicy: Delete
parameters:
  clusterID: eb53e78d-4b17-4e8c-8186-cd82025a8917
  csi.storage.k8s.io/snapshotter-secret-name: ceph-csi-cephfs-secret
  csi.storage.k8s.io/snapshotter-secret-namespace: storage
