apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:3Xa44JGRp+4L3eSrmu2S97D5ImuLPXqSJO8u1jA5rit6hepNG00vKAtHynuu0sq5vUP9qYfLAxpAuq08D2GBj/bI0xLK6gundPmL9DS8x+p7+goul3ARvTLYV2yftQJVfC0kpSO1PokgxAqNIMgUlqUxg9y2S/tmoRcjsgsWtDQWij3R8J4fDRxZIdxYpuU2YaEgVbRFiZQ4pyTSragRyMCoAKfkujQwIlmbwvKh/qyqFFNL,iv:jawmYpCHxQ2vdPs0FIxi0V3HCS7jBOk885mNCnKmHe0=,tag:RWl6M8Qq+uZpXidvgWX/TQ==,type:str]
sops:
  age:
    - recipient: age1v5nv69s859gf2494tevycyflcyezltjgvcss75ctgpdpv6wtu3fquywey3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNjZTeEVzR0JwTHc4UzBl
        SS9rNW5IQ2J3MjFBOGI3RHZiTC80ODhDTUZFCmlhcFBSa1g4bmgzem9QcUwwNWYy
        cEZmQS9nL2k2MnZoQXMyNWdEaU1RY0kKLS0tIGhNMVJWR3FVN2hWcjZ4R1VqS3NM
        a1VKalBqWGgybm1yZmlnSW1jNGJxRHcKlRxYXuFtnAZyEDOitAlqaSpX8F65ViVg
        lTLTWTp/9q4C4tuHTSUQlprBiFL1hdAaRJGcC4xh9ZoRqb1C4McnZg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T10:03:52Z"
  mac: ENC[AES256_GCM,data:OucpR5erksgGeXwPY0SqM/DbfKju5ArjV3sYmOEV4z8kc/jvXhrv8KFHnlpiHpM7l1HeOItiHt5Mdz8S+m8vo53eP+PoXMnzXvR26sEZt4HUXvMa0nLvBAmLdLmv+eg0NsYwRGUtX9d3YlfLPVDVTQjxFTQ9oNepS8xETMeV760=,iv:OHGtN0raJYvtn3nEb3tfKQYYnQjd3mhXN7urWo+nKxo=,tag:+Ofy3uYSzLrwM7cjJza7Bg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
