apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:TQHogjSOvTvI90hggtoK7yBOzkRqwy4402QWznX/jP/Lvn6k06K/e8I1NgqCuYDPs/XY/uAwgvBY/uO1zpMsGolmuS6l6GkKCmP961FyTJ7Diq7TXKxyHph5gkO92qCPhjf8ugsq2UNHDQQa,iv:qwR4qvtNDENi1+U3nHKUV0s7yA/8UXkuiXIUp1fGDtk=,tag:DAD3Wz+W+25Fc/dmFbwuow==,type:str]
sops:
  age:
    - recipient: age1v5nv69s859gf2494tevycyflcyezltjgvcss75ctgpdpv6wtu3fquywey3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYN3BpZHZpekVQMXV1UHZ5
        MmdWZ2tjVlJMQVVMdTN4amZ2ajFpK21uRFdJCm1GTUFxWnJvbEY1VG5wZ1NXbWNE
        UUwwSyt5MGh3c3FkaFBGUlp5TzluR0EKLS0tIHpuTUNHOWU3ZmJlYndVczRmTEZG
        K2J0T2IyMGlZSWxwbERob2kyVHg2Vm8KwBlLNZcshz7Lsh56+AckvXyOKOMD0XOe
        WrxLUODfm28w493fK8Qx7OnUMcanHm9umuR+wMVNNm0u/hdGkKPUsg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T03:16:23Z"
  mac: ENC[AES256_GCM,data:tVUXpnLe7H+owdlSDdEzR0Sm1d78vaMTvx2AnuGE0SOC5/lpMuIgMKYs1cUlglS740K3zF9VTKbC11RbQmpM//2Uf6WqcBW5PXEE+GNkCKzotctJy9e4V4dmfJuQcm47lxUPUJcSF/+/AgfLgs7ZHK+VQHi+c8Ia3SV19No7CLA=,iv:VQkPhgQsS6C5JeL2KBO69tI6c2Q76Ep8tV8RhD4kGMI=,tag:Xv15PwkfTSkDoSXNsFNCag==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
