apiVersion: v1
kind: Secret
metadata:
  name: speedtest-tracker-secret
type: Opaque
stringData:
  DB_PASSWORD: ENC[AES256_GCM,data:qVWGms9cenBatMzAw1Cm2rCTvk1bq7mnvur+ezlnn/M=,iv:r2mffWdp5B1+Y0Geh8bgDLGoMM1B4JC44Nbanckfp3Q=,tag:wrmDZyG7Td5VseKLSVP5og==,type:str]
  APP_KEY: ENC[AES256_GCM,data:fqAJgMaoQ3l9xUn7rIFajS7rG+tyJAJO3lLqI6ugF9dbw20ZkhWj29qAs+6CyWSmgqOG,iv:62RZYfV+hZDgC/Cx3whLhT0OAy13skvAXs35CT3s4YQ=,tag:E5KJPgNITVHE8Hr2zWIPCg==,type:str]
sops:
  age:
    - recipient: age1v5nv69s859gf2494tevycyflcyezltjgvcss75ctgpdpv6wtu3fquywey3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZlNuQmdiaUpnUTU3VWdX
        amdrSG9hNTJ2c05WSmhmdGkvZHROMDVIem0wCjdLY083ZE0wbGJkbTAyRk5qWjRO
        WE5HV3FSWlUveXZxQk5RdldmZmROL0EKLS0tIHlObS9lbzBkaUE0M0VLcG1DZ09I
        WmRmUW5oWFU1azhLaWpKWWRlajV1N0UKxi7JsZLPlKoXa51yjAepHL7wDQn6yyVK
        QMkqS9Nu4LaUQEHeD+u0Ov9DgV3JO7oGeqQFdPFLnGR31s0av7lYmw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T07:07:16Z"
  mac: ENC[AES256_GCM,data:TxweLukfFt8gNlFDw8Ugc1FRvmb8htvyzXWnBPR3IgGZFq5s6vWWlAr9wuejw5dxuQaF+7qWgHZxmpJZ6C7wvFKAIXVdPAChEKhgwth5K3MI2HdRHkGyvOepWL0fNipe86pHsyIOAZgdS8RHZVe5BV96Ve4fv5ryfnBwUUWYyEo=,iv:6UOw/6PWxoPlu9rUA189BSaZzUjGHf9qRG6cU07n37A=,tag:3tWi1cRmKGQE8j4l0KNTcw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
