apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
type: Opaque
stringData:
  rootUser: ENC[AES256_GCM,data:Dl2jEBY=,iv:PPD0BmeRbhqP2uzPtgcd9CSKqwgtrpgIdxWrb0vJpGo=,tag:3l0mHK+ir3QggPDTdlZRjA==,type:str]
  rootPassword: ENC[AES256_GCM,data:1cSAzjpa6KQGqAucN0TwSku3YetZlKUn,iv:NHlozg9A+q131+R15S3FS+SD0LBC2cZiokSpg1b4gYo=,tag:8rO1hRQMlX1tG7sd0an29w==,type:str]
sops:
  age:
    - recipient: age1v5nv69s859gf2494tevycyflcyezltjgvcss75ctgpdpv6wtu3fquywey3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdFdaSy9MYzYrSUVodDBk
        ZENYZ3I4aU5kbHJERjJsNnFYUEI0ZVVYWlRVCmpZRHNVZFdZcWNsVlpQUThUMitK
        MkJ4bGw4QnA3OHJudm8wRnRHQUJFUkEKLS0tIENHYmJoQVgrVnhtL3N1NVpDcFFF
        NEtFelBiejRZTm9abW0vS0lpcThRNkUKOeCoZECdImHxn3MX106WnnTxxFDqnnKE
        ZOMJdR5HRVJ+orY3WETM1EzXOl4ecjETlpfKgJFT8FdSFxYwzRxYSQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T23:40:17Z"
  mac: ENC[AES256_GCM,data:jrcZlbb5sRVtIDO5182cu21ACSS5OZEqNYmxMYvGyApHowsWALeKEY4kjnADM45A00gpr0DSRge6i3+KYydjuwsP+6/7TsPYNfJS16WxTMXdqvPKwXwRxKeNtshN0uhuNCOaGGyOi7BW8XEKV2rn1zAH5UtRLdGIcQeRQ9SFVrc=,iv:3oOYKjpGZtHC9+gDrTBXm5+iwCZB81FPk1NgkZSgLIc=,tag:0xas+whXCUO3XoW9XDCQSg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
