apiVersion: ENC[AES256_GCM,data:3Cc=,iv:wdjvCWQ5clXn0CRKzPy5zy4PL+JG73MP175KWUHxSIs=,tag:fq3S0Kqmte6K1QSFZ/Jlfg==,type:str]
kind: ENC[AES256_GCM,data:NTdZNnwm,iv:LVDuAhql2XXRBOCxlQGHi2wyMZykpcIlVgVls1wnEhg=,tag:QTMXnAR4epLurQUFYuVC3g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:pjw1umzq+cLEakuq82YL4bE1vfs=,iv:SIsqEKIutp+5pagQcttflNcv7fxnT0Z3B1Z4tLz7ALg=,tag:ropx49w0VR8W02v91EeYaQ==,type:str]
    namespace: ENC[AES256_GCM,data:kpI6TYulJJhjB2J0,iv:4eDJ9Wms9C2tkyvBeVCgnFUKJ+BUgSRvrpIWaDcf52Q=,tag:dY7ufPeNdd0sAlqOo6wO/A==,type:str]
type: ENC[AES256_GCM,data:08EKtctu,iv:sePbqBxgiFLz3RgMwNOPLsQTyXqMZ4/vRIrJ/g36IPo=,tag:GiKQ2kyOrAvCR+mwEZl8sA==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:okSzFZgMYyWSsGZz+in2N3XGFmjTEVtDK4SXzbCykQ1OGgvPzOO5qA==,iv:l2I7CSuInRUNpKI5UsgAfT2F+t+13afm9n9KTI50OkU=,tag:umWnhUtCYxeSsbiVUyC2hQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age172xllrdj83jnxh366qaqqhhq2gtd9v34hx85d9eypdnd6wsejp7qsheu39
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2N0tWNk1xQ0Q0eEp0YzNj
            WFZQamw1OUQ0akhRMG1nTDZjSnZ1SUxOZFNzCkF4Y2FHcm1lTmN0aGpsZGhmRWlE
            bm4xT0ZGODVUci9kMkQ4Y3pZYnNIUjQKLS0tIEN0NHFRQ2dyVitIV2JpL0RmbmRt
            QzZYOXRKZXBabWh5OVk2andsVkYxTkEKfi4irLXAOIbWEZDSIO0/piQYuptyNyYV
            r0MoeRNDRaY4q0cAdvvKFJfzu31FJ1/ybSJ2H6d1bLUlRiJU7ROi/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T01:43:21Z"
    mac: ENC[AES256_GCM,data:lp1T0xam/o7Sook8lVQQhaFGzTYgcHDWM0GgcKGzgMsKczIKKbfdhqrs4fe0Pa7uKevizPZrWsv5db2GNjX6sR4pve+27V9uZLRsN1w3nUxkH4RGctJ0KXGkW5/RNKJ3HzrtQbgc2jFSPWaVbUxUsPBqhCKw1pGD2ZE+RFJY2/o=,iv:C1iKExLRapBzQd9uGqSiWJg4mAIdgMYqwXVmAClGywI=,tag:T8kAC6GX9zETmUGN1dOyeA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
---
apiVersion: ENC[AES256_GCM,data:dFQ=,iv:G9+bTnAOW9XxwZeFPg8wVlIu9GNlkE429QX4nc0Ao0g=,tag:RPaPF3jlaPA0Nr0H8JmHpA==,type:str]
kind: ENC[AES256_GCM,data:Ar8Z/Y1B,iv:EgX87UqIPZ+gkXosBai4pxnzeKVclg57kHy4WB06i8o=,tag:BgasuQmRUNsCCvLu+PNSjQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:aAvKjS0F4sS7GEQZHCwWlcp+Rlk=,iv:KR9lyPWGFre2hoK0edQ8wr3lqSerMsizxmN9KcKLIlc=,tag:UApguaI8A6mx4trKRIN1bg==,type:str]
    namespace: ENC[AES256_GCM,data:xn4w2lA7kJjxVhiF,iv:uWhAIEQWRwSEp2ZpMGfF1d5sXY5IjV3h+9KfEZE3gGo=,tag:E4Zen3acWhm435zvXa0LxQ==,type:str]
type: ENC[AES256_GCM,data:Um9v0ItQ,iv:DN8TD6UVU9GlJo4CHTf0821zE68DtLN3O4GkH2zysCk=,tag:o0HYxnfSl5K9uuoWdYaEZw==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:M5BRxgZLYyHoeYV/RZQ6NxtqnZiH5EmhVpQWw7/UiSnIMd9WfRcZwA==,iv:dDQHHahe97IcJE73cJuXvuGEr0bq393yyyMP1lXNQuQ=,tag:hRAZbQVGmHErKCHzDNvrkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age172xllrdj83jnxh366qaqqhhq2gtd9v34hx85d9eypdnd6wsejp7qsheu39
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2N0tWNk1xQ0Q0eEp0YzNj
            WFZQamw1OUQ0akhRMG1nTDZjSnZ1SUxOZFNzCkF4Y2FHcm1lTmN0aGpsZGhmRWlE
            bm4xT0ZGODVUci9kMkQ4Y3pZYnNIUjQKLS0tIEN0NHFRQ2dyVitIV2JpL0RmbmRt
            QzZYOXRKZXBabWh5OVk2andsVkYxTkEKfi4irLXAOIbWEZDSIO0/piQYuptyNyYV
            r0MoeRNDRaY4q0cAdvvKFJfzu31FJ1/ybSJ2H6d1bLUlRiJU7ROi/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T01:43:21Z"
    mac: ENC[AES256_GCM,data:lp1T0xam/o7Sook8lVQQhaFGzTYgcHDWM0GgcKGzgMsKczIKKbfdhqrs4fe0Pa7uKevizPZrWsv5db2GNjX6sR4pve+27V9uZLRsN1w3nUxkH4RGctJ0KXGkW5/RNKJ3HzrtQbgc2jFSPWaVbUxUsPBqhCKw1pGD2ZE+RFJY2/o=,iv:C1iKExLRapBzQd9uGqSiWJg4mAIdgMYqwXVmAClGywI=,tag:T8kAC6GX9zETmUGN1dOyeA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
