apiVersion: v1
kind: Secret
metadata:
  name: seerr-postgres-secret
  namespace: default
type: Opaque
stringData:
  DB_PASS: ENC[AES256_GCM,data:cpF5tzfK101zON82P/P4O9CG5UmJZG84plp/vwBmXcs=,iv:3bynjJkN0XljpYZWwOVrOlFunmRMOQUV0nsvBpIIm0s=,tag:eWdTmAV7kbsrLOjzR0I42w==,type:str]
sops:
  age:
    - recipient: age1v5nv69s859gf2494tevycyflcyezltjgvcss75ctgpdpv6wtu3fquywey3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtYTJvb1RVZXFiYmJTTlAr
        K1BFYURYV05sKzM1YXdZRlk1cG5rT0NxOFRFCkFjQkZ6bmlkMDUyS2Y5UkxIV1Vp
        aUlRcnBBWVVTZkF6Q050d3drWHRJSWMKLS0tIDl6eE15aEpLL2xzSG83MjdIRG9I
        a212RGp2Nk0rUlNCSlVpeFlHcGFyNkUKMp6UnnClqFYx3EKW9vb94uQYm2VX65S8
        5cN/iAQKtUJsmIHDGQ+LW+xaBzpZeoCg9ktGiO808vDpSls6Eeo/3g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-05T01:03:01Z"
  mac: ENC[AES256_GCM,data:mrIFpcxZLwZAMEQeCInPrHb033Gu5+1G9hi/VI5OmVfCiVIJvk1Bw8yQUfPi1ZHdFTm180m3hZr+riN3+u8YrNAvgTvUDDKEQBqONQ3Yya1bM7cHf3wCCendlK43ggeexZ9x1h6SHFHRhkxtJXLXGZTjpEb4Kfjsa+yHOwcdIwQ=,iv:FA8Agfei4G/I160FA8YmE99J3y7I5LZ4uQ+JVa8TvFw=,tag:wqyNQ1SjJ35vahIkr4w0wg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
