---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: unpackerr-config-nfs-pv
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.16.1.250
    path: /volume1/k8s-backup/app-configs/unpackerr
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unpackerr-config-nfs
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
  volumeName: unpackerr-config-nfs-pv
  storageClassName: ""
