apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:X+bRUvF/+lzpImDJgQvo0cnFoYsph03nJsBuPvOw7JA=,iv:NdgIrD0Li4C/saA/ZflCkjB+dd+hKlfpr9UuqsKZUK0=,tag:Q6EAH6wsYOdjpD9HpPPXIg==,type:str]
sops:
  age:
    - recipient: age1v5nv69s859gf2494tevycyflcyezltjgvcss75ctgpdpv6wtu3fquywey3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6eXdyak9KVHAzTmRyd1hY
        Q0VUbWZ4aTdZZVdaeStZQTZjckxDVlpVUlFBCmptaWJ2NDQ3UHFYb2I1Q3FKeVJQ
        Rm8xQnVqbnJ0dlp2QmpPTDBnVEFUSHcKLS0tIDZqR0xhdld2azh2NndxdDM1TTM5
        V1gxTUJ2bThrZnY0d1FVV1UvNjlPaXcK7JF2U3P7bt6q3YPa3GH5q1j+hYAI0obc
        nXLTgrfDwstRzFAn1MDvP14aPQwYg36BFITHW4VZObvJUqRlyHEYig==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T03:16:23Z"
  mac: ENC[AES256_GCM,data:viucp3cabd3066RdQCAY8GqnFxt0m26DDaZW/O+mONs6ys69c7ilE5Bj59FNVxn89qL9ZgcGAkfEow9MDZQJ7dJwOKnABQR1h4c2DCdaxFRMWSSrBBZlkEQ4f53xGlZ5Cck0LHhwDKfbxqgen8OpE6LRmXZexnriuggHdRwOpDs=,iv:qNbjPxQuUgOKapLbRKyVxw/LzeSeGrFoKBX5dh0PxYo=,tag:HH6ze58f3NkEkS8UjQqDpA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
