apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:nz8cg+72c3/MvlSMybss4+OIN0e1O8Ej0MHW/WAQzMX4EJXlLBn6Cg==,iv:VnWGROiWW0IEUyS3u/zmzzfaki4M8zRKZZOfGxhvnu4=,tag:e6siSikLRekOhrbf2yoMkA==,type:str]
sops:
  age:
    - recipient: age1v5nv69s859gf2494tevycyflcyezltjgvcss75ctgpdpv6wtu3fquywey3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVGpYV3JSM0RZSDlPbXNC
        NlpvOUgrQTZHYUcvN3h6T1VZSTkrc0FFc1RVCjRHRTY3NXA5a29qWWVPT1lNOThW
        TDU4TkdZeTFSeUFKL2Q4dTBDU1oxWk0KLS0tIGdSVnpHR1dzeHlIL1pMTXk3c3BF
        Z2dnRzdlMHA4THljbzMvNVlQdUlTbkkKmwrvj109qYmo2tv7X/CCHQ8ZoNVdWYeu
        1YwCWZIcw/3pJf0SlMESv/TQLAB03MC54UGx3Dg4E2D+/AydAIGl7w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T04:42:06Z"
  mac: ENC[AES256_GCM,data:h2F/6+s/AFxcEWqKfIL5hDC62TarIE39KKWXV1SrAhOIhr2TlsKtMDPkzY9sPjYvk8hZbgBkMOW6HkV3a22X7mCLfkSefTieJ138vHwRfo2i+fogMDj0zCj/u8M7Srn4gafsHfjGBAx21BZk2KQYQA15Pi764Vo+3oLGLwuKmYk=,iv:qvgzSB58f+5UIdx2+bKvRAeWA4XP68VwIotXm1kL+JA=,tag:8SVWQSNhLw4MXM6VAdLeEA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
