---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../../components/sops

resources:
  - ocirepository.yaml
  - helmrelease.yaml
  - httproutes.yaml
  - loki-datasource.yaml
  - secret.sops.yaml
