apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
stringData:
  admin-user: ENC[AES256_GCM,data:d/HmSqM=,iv:CsOR8wppZr+kXlf6zvY8c3zRU1Ayntz2L7VwCarTZ5s=,tag:ntq/D3edIGSrSDLeQedGag==,type:str]
  admin-password: ENC[AES256_GCM,data:gKKb8rm1nNryqChE7BBODGNmlQ==,iv:xrvZULUU6azazRzOZiQlZGz9kPM9J+6m8gva383x/wA=,tag:I949gZy6wv1yNObK1sizsw==,type:str]
sops:
  age:
    - recipient: age1v5nv69s859gf2494tevycyflcyezltjgvcss75ctgpdpv6wtu3fquywey3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2YVpuOS9lTGZ1YTJZbmtz
        cnBzRUxUTG1LcTEzUzd4S0NwRVgzaFE1c240CmxGSUE5UW84SVpRWjJ5QkwyeUpC
        WkpzY1NSMDdDTmZFeWM1TldvamQ5cjAKLS0tIER6aTk5am1LNTlEemhMQTJ1Nk1G
        ejJPSnozYXFzcDJEVHVFakpPSnJUVHMKEX+gK7NhRBY6ZesMalglxzQis7xaORx6
        vzlgCyD/tKkonED+ReENHxiOSxk62twvPkyhSNQYTMe9hXVLE5TXsQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T06:45:48Z"
  mac: ENC[AES256_GCM,data:s90mk3leceAeqPYf8OcXDACkLphbmIM9g0q0WcFFqzyUDnRB7DdyTYzOSXEiql+EDqucvJB0NBaUj5OGusMMnh38pd6sOEJdUlmYFQicDOW8teCnnUfEOneRPOFq3H7fFBJ8gfAJjnJse/5lR1GGymJ1pbx9Kgsbrk+hbc13ujE=,iv:bEUieb+Jo/o+I9rqvXURTmc8AeR0sQV8jza0230yTQQ=,tag:Hv4km3rnofjYXNw6oAiC7g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
