apiVersion: v1
kind: Secret
metadata:
  name: velero-minio-credentials
type: Opaque
stringData:
  cloud: ENC[AES256_GCM,data:5neZy7mQnQchRrXCOH6zo6jPhcxB9nYs6G2nE3pxxZttzUsnVpJCUiYR4V8rMxtds8i3BwtZRdBP2Y/Q61c3itDXj4L7hR2OEpc9DwaInUzk,iv:pt1Alnmj51+R9YvtTWO1OIhrcTZwBuhutpmKGl0cVr8=,tag:qQ8/TULVOOPpAUTLfcLcaw==,type:str]
sops:
  age:
    - recipient: age1v5nv69s859gf2494tevycyflcyezltjgvcss75ctgpdpv6wtu3fquywey3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbThuNGx3Q1NPWE16U0RQ
        aHRqM3FhdzhaSmJKTm85dUtSTm13bGVleGlVCmFCSTJVY1pkYTlCQWJITkZhelp0
        eWN6UzFiWVAwamdoYVRjazBycUg4OUUKLS0tIFRoK2U3eGYzY2JMcjg3QUJIdkly
        SnU3czZicTN1b1RreHlQajhaMjBTaEUKARTpExKVhTeG8qN5ayOCdaiE0rXXkPDb
        8FJAikKDDv8mbcljR4ei575z9K9OnM51Oywf//F6CNFT2vpPlL6+3g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T23:40:17Z"
  mac: ENC[AES256_GCM,data:e3mgalfL9Fajz9JKU/xiGRMEgaGNHObPd1cbSMoluYDAZJCVViz/c6JKiNDOVrIJxTI7l/5FdEwWqNWj1p09FVVltA1IyCad/PSBSlx9liflcx5hDQq27rT4atDYw+5QMloasNvrwiX6ZSEtpLom4Z/wIladNVADTDlIK5SsOSk=,iv:wPk1EtXpJU8wLSqLEsOJPrp2TXYi0lPcC12nhUADbcc=,tag:5JKSR0gbaa5tA/3VmbTGgg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
