apiVersion: v1
kind: Secret
metadata:
  name: overseerr-postgres-secret
  namespace: default
type: Opaque
stringData:
  DB_PASS: ENC[AES256_GCM,data:b55aY6LBSv6EzRU3Rci+dQmHa2lopN3H3Kfkk/it32s=,iv:qITnMqglxm5bwbj1adEOJ1NokKL77rhj4ekoAVVIHaE=,tag:crtDXKCr79DPyF/MmJA+5g==,type:str]
sops:
  age:
    - recipient: age1v5nv69s859gf2494tevycyflcyezltjgvcss75ctgpdpv6wtu3fquywey3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYmlkV2U2akw1L01ML0V6
        alphbzgrY0JNRjhZRjNscnk1aFFUZE1uaWx3Cm5tNUVIOXEwRkFFNmlBWGJnMFJT
        MjNLNWdHK3JzTjZIUG1IVHQ4MURoWHMKLS0tIE0xRU8zZE9uVVUvL2hkM21WRVZN
        aEZnZGUvc2g4Q3daUTB5QjZ6V0hvb2MKy2ndN38Ym1qvgb2yQZDtZkT7afLFQh4t
        nbSuJ9zEIGc1MSnZBcSK90FaHMkcvxWkUUn7uiBMGzWMRLukmoAVIQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T00:43:25Z"
  mac: ENC[AES256_GCM,data:3PmJ3tM0BqZFMHj5Ely7A/rUrrnlKW9RDX0KQbybedLKJGv08eR6t+ub1zPBfc60wZTXKTxYICKa1UxJDFdQux4oCvmRPIZb8adQp2elcPVVs/up4KWRB3bT1iewwy+VT56+CBBV8p927l3vOU98piqIUhXs2U05/m/xGWiaEvs=,iv:KFLqxRT3fwHxbpzMgX4lH4g5OVxtKdnKSFXqDkaCogg=,tag:8yntsrlvzEKb+UWpyhlUug==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
