---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ceph-csi-cephfs
spec:
  interval: 30m
  chart:
    spec:
      chart: ceph-csi-cephfs
      version: 3.13.0
      sourceRef:
        kind: HelmRepository
        name: ceph-csi-cephfs
        namespace: storage
  values:
    csiConfig:
      - clusterID: "eb53e78d-4b17-4e8c-8186-cd82025a8917"
        monitors:
          - "172.16.1.2:6789"
          - "172.16.1.3:6789"
          - "172.16.1.4:6789"
          - "172.16.1.5:6789"

    provisioner:
      replicaCount: 2
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi

    nodeplugin:
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi

    storageClass:
      create: false

    secret:
      create: false
      name: ceph-csi-cephfs-secret
