apiVersion: v1
kind: Secret
metadata:
  name: ceph-csi-cephfs-secret
type: Opaque
stringData:
  adminID: ENC[AES256_GCM,data:RscEIrs=,iv:sHOLICDgqPazQMIw0pjikKZMQXIaQ04OI5ZRgrg0ORs=,tag:XSZbowVIu9mjGfBx04yMEQ==,type:str]
  adminKey: ENC[AES256_GCM,data:xTT6gxfUDqXrdp8BOthWG1bmqHuJ2IkDAIvyKoB+Gac4XGcZFl2dcQ==,iv:MOU3YtO+MHzWaCfL+fZaMei14GjLZzAFZkKKWvYhpVw=,tag:0weXxXjp6NdEYe7NsSFs7w==,type:str]
sops:
  age:
    - recipient: age1v5nv69s859gf2494tevycyflcyezltjgvcss75ctgpdpv6wtu3fquywey3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWXczeWtEajljMlhwZWpV
        YzRzbXZqa0E1U1ZVZmNxZkZsbkZUeFF5M3cwCnNoY2hsMW1LSWNMR1FwRU5vRGhh
        VWFOOFVjdVozY0tWWG9tQ3JNTzg0Z3MKLS0tIG5MVUNNV1RzbklPV3V4WGlzVFg5
        R0QwaDB0QTlUY1hERUFlekVXTjVrSFUKST32WYFkCHteKyPF5m0+A51KNqG2nC87
        8iF3dXczZP61CBWU/5EtAWafAzflQMbJCdjeWc2cXjsZa9bNVl0c8Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T23:35:52Z"
  mac: ENC[AES256_GCM,data:raKt1BPOfN/5sjheBt/WPAzYJoALgWMQgolRcKo+YMuLywa8ViiqGUmqgpkdF2eETZZWXeA0K1+LeF4XbleqqXf4GIgSKKGmM4Sq7rfe19VgD2Z7fQ90X1YZbeEaT0g1ZwPu/61f9N3rGVlPhZWLpLzOFncH7pu0cluCfAtkuNw=,iv:RwYTlYazAUTdpZ1rKlrKNBgpLFhwKaW4qfPTuqtn2yc=,tag:XoPNtMxVQiS2iwyHrQfcDw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
