---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-filesystem
provisioner: cephfs.csi.ceph.com
parameters:
  clusterID: eb53e78d-4b17-4e8c-8186-cd82025a8917
  fsName: cephfs
  pool: cephfs_data
  mounter: fuse
  csi.storage.k8s.io/provisioner-secret-name: ceph-csi-cephfs-secret
  csi.storage.k8s.io/provisioner-secret-namespace: storage
  csi.storage.k8s.io/controller-expand-secret-name: ceph-csi-cephfs-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: storage
  csi.storage.k8s.io/node-stage-secret-name: ceph-csi-cephfs-secret
  csi.storage.k8s.io/node-stage-secret-namespace: storage
reclaimPolicy: Delete
allowVolumeExpansion: true
