---
# Uncomment and configure to enable Discord notifications
# apiVersion: notification.toolkit.fluxcd.io/v1beta3
# kind: Alert
# metadata:
#   name: discord
#   namespace: flux-system
# spec:
#   providerRef:
#     name: discord
#   eventSeverity: error
#   eventSources:
#     - kind: Kustomization
#       name: "*"
#     - kind: HelmRelease
#       name: "*"
#   summary: "Cluster: kubernetes"
