apiVersion: v1
kind: Secret
metadata:
  name: homepage-config
type: Opaque
stringData:
  HOMEPAGE_VAR_PROXMOX_USER: ENC[AES256_GCM,data:u3dSwdl8UGpEPfzGj6CCYQ==,iv:fX9EPsF7U4D8BDAJFGZus1FgKj8j9feiAfkqQcbzCqc=,tag:j5fva3aEJiWzvvpseejumA==,type:str]
  HOMEPAGE_VAR_PROXMOX_PASS: ENC[AES256_GCM,data:P67OvWvB4BJwWCDIfMFlXg7Kb85R9UkZ4wwhPC2PcwR0B/TL,iv:PIKnfJw1cydKnRIQ6sinMIkZSPvnA/sTRrFkSANCU3I=,tag:Bj8fuEkWas0r8FDZJr1S6A==,type:str]
  HOMEPAGE_VAR_NAS_USER: ENC[AES256_GCM,data:fqJH856+8xm1aZYH,iv:v3Oji0TgLgt35RpHW2IFz7f/eAFSRoxhpLgHYVLbBQc=,tag:m+NWuTm+He7lapaUsUrGMA==,type:str]
  HOMEPAGE_VAR_NAS_PASS: ENC[AES256_GCM,data:pem3Qm8tcIalrvJDrjLo4NNJISA=,iv:ZVq+oHHkTDJajkejHOKCy3UBFvgQBkXoN3AuErm+hoM=,tag:/MpvD7nwqnLff9XCv5tp4g==,type:str]
  HOMEPAGE_VAR_PBS_USER: ENC[AES256_GCM,data:SthHpD3KJm2DsVwXVqlGXPI=,iv:vL2gk4F1+xYb+M+Hl4BuVvO+yNZchFGZbd/59gJfpZw=,tag:3Z9bO2N2I6UfdqHqQgiqTg==,type:str]
  HOMEPAGE_VAR_PBS_PASS: ENC[AES256_GCM,data:KwgfxuM/4tQzElziL1K/Yok3sPzDWxpiZo+QE8MNQRkbBaBg,iv:zCJ3rww959jOcz3ElGYFXmDxOX8Fk+oFMaf9wM+iFn8=,tag:3cKC9fliPzGmw9dN1W6T+g==,type:str]
  HOMEPAGE_VAR_PLEX_KEY: ENC[AES256_GCM,data:OEelSqlEOYuTr/f+zljwLoQcjb8=,iv:XefHj/NDBk+nFstUL7mYwvrAagE02Y33ByA0PYlGld4=,tag:bd2F4PM/Ugqzbdya49tbOQ==,type:str]
  HOMEPAGE_VAR_JELLYFIN_KEY: ENC[AES256_GCM,data:9Nj8c7PmaHaM7if/Oxp5SRVXil/p3TJbsEFoGxqrxZY=,iv:4KS+7U3rsvhynD/mIuPfTHr7xUj9TW+XQ3hr5nTYZY4=,tag:WurxQ6aqVN7P1ItGLBB90w==,type:str]
  HOMEPAGE_VAR_TAUTULLI_KEY: ENC[AES256_GCM,data:roAYR1m5psaqz9TheTKWAbndAKEQeh26o2DisNB0NOM=,iv:lFufVM+n0m0MqxdkpAtnmFYE+WoPfBe0cfFEgm8UQS8=,tag:hpWiM5Vu+oYz/qbM25HTQQ==,type:str]
  HOMEPAGE_VAR_OVERSEERR_KEY: ENC[AES256_GCM,data:Xu1dHzJrZ8SxMLA0Rr1SrNjBK6hh5kslYwV29v6Y2w4EK96aCGLfqPuxjVkTFA0b35ew9T25qTeLfVSIh8/rrlSVK9w=,iv:IOy4so7wvKeK95N2KkOkYIvT9Ks2gzVwf9tZbq3kOeI=,tag:jjLi0ndcavvdQndYJ4iBiA==,type:str]
  HOMEPAGE_VAR_JELLYSEERR_KEY: ENC[AES256_GCM,data:dg6diyiMhcyhRw8kLl1Rzq7uFmKEqs9svY84gAh3ehvolyk5j+21pe0YDR/auwPC1AFPOA9YlzwDBiTbIvBTx02EoMc=,iv:ahSBvBVpqMA0ls1+vIg51TF+RLDNnzsoFrx4N5sF3pA=,tag:ccRqDXRdYvt1Z2ZoPJUxXA==,type:str]
  HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:bzJZQCSBfvSsx4pBlGG1nCeFR1n6P/KG/CSBL5XGRAg=,iv:0tzdufnO5MpXxzBt6q4yqbC47ilyrZa47z1bm3U3954=,tag:qJ1OwhcD6e9OAah5iWD2+g==,type:str]
  HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:ZsofYI1JoUinE9uX1KQKrYnCXQIfiERtndKAnvrbZAk=,iv:yWVNAgFNgKtnI/kn7tzC5sbHV53v3RVFZJt32s+eZu0=,tag:X0uGp8rEASqxmJUyB7HW7w==,type:str]
  HOMEPAGE_VAR_PROWLARR_KEY: ENC[AES256_GCM,data:qkfFc3DmLi3zToyBEJKYbKtEPX1qfNvWjocWDHeZsSA=,iv:Fblp9D1pLMGbR+trq+sS3OLiznOawtvUMw9ttQ1FUvo=,tag:Dvu3eY0OUj6Box8k+ZMcew==,type:str]
  HOMEPAGE_VAR_OPNSENSE_USER: ENC[AES256_GCM,data:l5rJ6S3Oz/vNQ8PGvcyXpdSlvhb8J0lZMI0s/+lsicYntuvZF61NT1hbD4Q4Y1+RFZDp/Zzi1AzJGqSrdKYED0lkSfLYwi8IM3pZ1zdnIto=,iv:AiLA4ShSszrx8F4ok53AuiBX4Ewps5lAj8KueTbLQ0g=,tag:aBQBO30q8qnu6zHpboVRtA==,type:str]
  HOMEPAGE_VAR_OPNSENSE_PASS: ENC[AES256_GCM,data:Usd1NNGWKwW4Yl1y89ncr4lRWO+axTa/VcqrIqvr15sDF1adeevXdBzmBqeEXi6ki2R1EqL4+bwr+r9bPGFpJrWHb0aDSUaCEe9ncQwGt2c=,iv:Am+wY2k2kXid6Ymq5zMpoZYrK4171BRGKTQUjMc6Zug=,tag:bV+QXb2R3iGzpmbG2vOvHg==,type:str]
  HOMEPAGE_VAR_ADGUARD_USER: ENC[AES256_GCM,data:TBJI7A==,iv:MITBD7jSz65xL7ksv2kTQQHPd2EKX+eHbWdTTwyF0cc=,tag:H4USL8W7hQwoO5/T37zbBA==,type:str]
  HOMEPAGE_VAR_ADGUARD_PASS: ENC[AES256_GCM,data:bTMkCKHtrF8=,iv:IAn0p2yOaRsuesncTId8lYiJ7AbVrOQwmwyNwU1ydhE=,tag:zRPGfkYVAm+YReYr/r57zw==,type:str]
  HOMEPAGE_VAR_QBIT_USER: ENC[AES256_GCM,data:XcKyFCY=,iv:zmKXgZFmQR75SEZTSSbbHJCNZH+IkAcEJVznLWn63g4=,tag:/gj6FEHtSG522IVFnzZvRw==,type:str]
  HOMEPAGE_VAR_QBIT_PASS: ENC[AES256_GCM,data:ZViTBJt7GWk=,iv:nwT93kQuiVx10pE/WpkQrI+mOd/F/JRLsF/tVE0PEo0=,tag:Uu5kt9b+Dx7JwvtL2ICwQQ==,type:str]
  HOMEPAGE_VAR_CF_ACCOUNT: ENC[AES256_GCM,data:mBfmrsVLhhyvTLe5Kfv+/4Y57UzTz5BmleGjRxgAIjQ=,iv:buudOP+Hu3EuDCY5wssjkCd38LXJoW9YXGgBHktvsYQ=,tag:f9uzjLFzKAhRdI5Xc29SIQ==,type:str]
  HOMEPAGE_VAR_CF_TUNNEL: ENC[AES256_GCM,data:6B089sLN9+S4okiTxS56bh8KHBlssoMsqZCb38IGdKuzFJtz,iv:0fdq9u+aoqLVPNLY2QNlyQJA3P2oVwmiijxch/c+dXM=,tag:NZ/wsyZDANqfIpHUcHBqAA==,type:str]
  HOMEPAGE_VAR_CF_KEY: ENC[AES256_GCM,data:lLGB7YD8d6GU2FyXGVBnkkGPxQRI890mBoWIIwcfcGyWb6z5DNpX6g==,iv:saI/T8992Pt05wv8+0A8wpS2ZtYRCN+kt+iTmBzSux4=,tag:yNiXs7QUSABVABcb4BtGVA==,type:str]
  HOMEPAGE_VAR_TRAEFIK_USER: ENC[AES256_GCM,data:c/SaXSE=,iv:TSpZ6/tfU2hUtPgclDMbWMj/forlc270csm+p3IXZBo=,tag:PoL3y6dHLWjiGlg4gGkWPQ==,type:str]
  HOMEPAGE_VAR_TRAEFIK_PASS: ENC[AES256_GCM,data:6rn5iXlRjJw=,iv:Tw3iQy96A1AXEy76e2RbUY+lVlgawiuK+FIqYxJdNr0=,tag:P59xAQrfEK4uXIChaRdWxg==,type:str]
  HOMEPAGE_VAR_UNIFI_USER: ENC[AES256_GCM,data:R/MQ3d4A33p/CHwFgcJD,iv:7y1r4Kjjq1Kzh95RQfjdDfLMKqY7+tG+KYWO/SkEKTY=,tag:sJDmr+AcsC7IQxTKMn9+Vg==,type:str]
  HOMEPAGE_VAR_UNIFI_PASS: ENC[AES256_GCM,data:OZiI3rax85o=,iv:2tMrsBktAYkRRgcBvLorjOlPz5oxNA2sfqD/4YxqDPQ=,tag:IjxCDRMobYDvs4HS++kJvw==,type:str]
  HOMEPAGE_VAR_WEATHER_KEY: ENC[AES256_GCM,data:vhGE4jtFSY5F8eV1NwpR6fl2jOIu+KpTMvCaoEc+sdQ=,iv:oDTdjTHsLjM1komTEPYiePsgDYJX8yItzNJQITDNhU8=,tag:smZftgSYU3IkxDS05kPmkA==,type:str]
  HOMEPAGE_VAR_BAZARR_KEY: ENC[AES256_GCM,data:HQAY3CEd/XAsVbcS9IswKVZPznubwjPIFVgHMguuPfs=,iv:H+gVfFhFUWEIl7TH0QA6UBY6DZo3Lq/4P/ivV0FfsWA=,tag:lTAi011PyMLvQMLA5OkLHw==,type:str]
sops:
  age:
    - recipient: age1v5nv69s859gf2494tevycyflcyezltjgvcss75ctgpdpv6wtu3fquywey3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZWFKNk9obEYvamxEOTI1
        MVh6d1AxSnFiaWNsMmpZSXhsTnlOQWluRlZrCm1sSHNwZjhldWJJb0ozNGVDS1ZX
        YU9wdURnVUpRZElPVS8rcUpURE1xYUEKLS0tIGNKd3VwK1BJeHYvd0VXNFVkekl4
        TzNaVTVHQXNSa2h5bGU4c2hycmU0MnMKK0sbbSedgFejkPtFtEuT6fV5T84KUP2L
        CGHeApdp5d5nGCvpRcJoLXoAPTBIZHWrMOmi+axbH1Ef60kxhwy7Aw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T05:58:20Z"
  mac: ENC[AES256_GCM,data:8uB6/Dv6kUTzwGzTmzeXhXrpONvC7kmn2EnYQAFWrt60BqErf/J1owZTEL2yfRmQW859iTUerKhgygaBbc1KrK0hCbAo9TUj3db2UlzMDcRz7sjoUtM1bdUZEJvwskp07+llFkzSXNWctyQOAqdPLtUTgGJeaqb+ZquPMEYVVPQ=,iv:XKSIy3L4/353JQIuNDLvso3hKhr9yoiWYFTJg9XaiKA=,tag:FBN5671lApnb5AChqpi3UA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
