apiVersion: v1
kind: Secret
metadata:
  name: homepage-config
type: Opaque
stringData:
  HOMEPAGE_VAR_PROXMOX_USER: ENC[AES256_GCM,data:ybcm+OmzUsrQTP4bYdA60w==,iv:8xkV/8qcslOlyuEMOL+AesNOttsRUy63nJnNb5cJ0iI=,tag:xdKH9UO/Ft9Iy1lNi/kMEA==,type:str]
  HOMEPAGE_VAR_PROXMOX_PASS: ENC[AES256_GCM,data:8FQKwKahaDetuR99OYd0YZsylD5RVpAA0vYhJB6w7CxtJbka,iv:cC0XLSDsZ55G/qv8hX05sJ2q3DFOSVW7QvYsRIq8W+Y=,tag:QESSZKG4f/bl+sLx6ow4iA==,type:str]
  HOMEPAGE_VAR_NAS_USER: ENC[AES256_GCM,data:Uo5GBz3EW7YSkksP,iv:kz9zMJCfkEyRa83y093STgNJm4EHvyn4mMVZyD89lyQ=,tag:QLY+2J1kR4fF97ZgbWU8EQ==,type:str]
  HOMEPAGE_VAR_NAS_PASS: ENC[AES256_GCM,data:BUcpU7W9r7UcefH5Hy4ula6pg+8=,iv:rWpakcl6ZzQT2bamky4xTO3RhYNDNl99/NuI6xtZ4dg=,tag:o0lKhq1YkcbBDyERYD4/Qw==,type:str]
  HOMEPAGE_VAR_PBS_USER: ENC[AES256_GCM,data:BdvrwSvInTBnUUaTqZyNVqs=,iv:LIGhcd9u8QBipNdR9oTA1fkbOjtIxwo8n4K5leHLVek=,tag:GPh/BQdxoec2xFOEFW/7jA==,type:str]
  HOMEPAGE_VAR_PBS_PASS: ENC[AES256_GCM,data:VzGAFDZO+4+X3FM5VkWmL6M/ga3kg1Lu5wFQeV6Bza/u8+cF,iv:Vdh1Lc6jkiCf0nYAYc/ugbdPbOtpSEgBjd4lsL2Hy9s=,tag:oueQEyP4lTXWsKU+hOm1/A==,type:str]
  HOMEPAGE_VAR_PLEX_KEY: ENC[AES256_GCM,data:U/P5wu3TnrMiUIT6zOOSOs8AzUg=,iv:+ZJN6RE5m5id9NI3eM5NTXlhcAViHsXm0ijVJpC+6x4=,tag:RVupPDbZz7D3DxbaK8ad2Q==,type:str]
  HOMEPAGE_VAR_JELLYFIN_KEY: ENC[AES256_GCM,data:C2uNkSEdFVoj9ZdVTVkICshBcWiUZxGO4DtPcd/9Qa4=,iv:VKoHjoY1JWUkSqn3a6FRdq/iq2FSpg1jl/NU5PeYSkQ=,tag:gUEJJ+6lT/da88hToq3SAQ==,type:str]
  HOMEPAGE_VAR_TAUTULLI_KEY: ENC[AES256_GCM,data:eAIBe+ALCcIHlf4ORaNG+d6UWVdLFyNFDNAg8+zkLE4=,iv:/MBLKDVOocbDf/inhNmB0JFeW1mVzvDWWb5uHLxgSa8=,tag:00SLFWCrwi302SeMlH2LKw==,type:str]
  HOMEPAGE_VAR_OVERSEERR_KEY: ENC[AES256_GCM,data:TIt7XTcso7U4OZgQ+i6bq6oNW+X+OND8dfwg5NwoJpH2OmlaOeAP+t9UmmyXZgt9SW//DnJJhMiCLw1mlaihePHatn4=,iv:643YfWHdz6qR+6gwJPCdFnMRllhEfG/3hIeR8vKgKGw=,tag:9WGCR6LngE1ZnQBV/5b0QQ==,type:str]
  HOMEPAGE_VAR_JELLYSEERR_KEY: ENC[AES256_GCM,data:LP8xP5EHuc++6y2BCJNQ7F3a3SKFiOaNsxVBbRRP7WPvOL+xUkkrl3iiPOLnrR1VlP1WmtVlN1Ecxq3RAXZI86Fin1Q=,iv:+TUAcI5vcmeav9UkiqEUVo1E3P2RR36h5zYezAhDpVA=,tag:+SrI0KwQHZWraZBGkLRJIg==,type:str]
  HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:7XeKJ3yPiFguRuJubOJ/biYrc0apQ7pq6tJQdxu24g0=,iv:7qXcB3DHWWyGFYHNTz2JNTdNrOJ4/2CoLYfGgVEujRk=,tag:Iv9LwFb+KP0OQlsMuazzGw==,type:str]
  HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:Rf4thcj4G32obsYpy2hGCsfNxPXzYfxtVq7/t1jx+aY=,iv:VogwJkzOTkVC76aTRtSxaEXuUGuxXS8UaGiOI9V1pRk=,tag:1L3v+doVrjQZC1JfLwOBdQ==,type:str]
  HOMEPAGE_VAR_PROWLARR_KEY: ENC[AES256_GCM,data:XcQdHVJJuKXTQtbJ+vaEJKC7dEn6ySkn/Plo7lIkvm8=,iv:eooxmzVXXcU2KCV37KLBYA6BoVdZ0sfFTi6wlPef3uw=,tag:QkEWNID4pFFdL1mJ5QDoFA==,type:str]
  HOMEPAGE_VAR_OPNSENSE_USER: ENC[AES256_GCM,data:+T6ZiLcelf8z1uhuafuGuVnvYjAhlaX1fGLb8fnz5QWnf6ip4OM0udXlk2+CYt99Fg+rsDBwi5znqvefQ18qzEL8qV67JxuQqHShQpC2Ntw=,iv:z1hNgm82wCbGWd1g8fXrNSelp40d/PFdAgmRJK5OH7c=,tag:jNee/tKb/JNpRiFzNHXdCA==,type:str]
  HOMEPAGE_VAR_OPNSENSE_PASS: ENC[AES256_GCM,data:syrvsPBqk1xhvePMsAr67DmCgLBZeDPvuMwsuaiDKhHeELQQko5x3TD71ZHejS7kpq4/h6k80cQl5oSHOWH/Tk64tW7nuRH17cBhQXnmNc8=,iv:9+jNBtf4sTXFk9zRF6Bc/fakYqcqqKaBzYrDU78fRBg=,tag:rlN3zXWbHu98A4m2BGPQFA==,type:str]
  HOMEPAGE_VAR_ADGUARD_USER: ENC[AES256_GCM,data:AN41zA==,iv:vHaK8disY+7ZIdJJEaPh1XJA1rCBMiFNHR9hTXgdC5E=,tag:PLwxT/WFP7SGdWgI1z/VlA==,type:str]
  HOMEPAGE_VAR_ADGUARD_PASS: ENC[AES256_GCM,data:Mp8U1mzNoiI=,iv:Q+FeQ6LynrGbZPuzEsq/r/NPjo2LNWwpkblsPAvtQqQ=,tag:aVdH0Bx7MhWNQhYdRtGddA==,type:str]
  HOMEPAGE_VAR_QBIT_USER: ENC[AES256_GCM,data:nJwI8fA=,iv:N5+6//m3Xqsd5pjwP6QSE+yTsOsLkzhl+KIPa+lugSk=,tag:xhFfnhiMUp5vSFK/fqrYOQ==,type:str]
  HOMEPAGE_VAR_QBIT_PASS: ENC[AES256_GCM,data:c+AUc+Zy6U4=,iv:KskKoJuw8MZvfbo/UyOiSQ4C++i6W0uemk60du95rUk=,tag:2RngpuDOuKFY/JQiO1cwkw==,type:str]
  HOMEPAGE_VAR_CF_ACCOUNT: ENC[AES256_GCM,data:fmpopPYV3DDecAfS0JESeqzrgPyiJz7haFYc/KM53TY=,iv:uGwpsvRM+HRFbCNeQmDnKJla6WOpEkuiJIZatPcukVc=,tag:ZaeTuWBCwtjHHJzlmCchwg==,type:str]
  HOMEPAGE_VAR_CF_TUNNEL: ENC[AES256_GCM,data:FBB8xi/WZOw7Z19IXyafdl77kwCmVF2hJNTZwUkNfB9KIeZ1,iv:v878LlpMYu38MMsFcWrDiTrQNrYET0LfIZFO/MrKp1c=,tag:Jy3dW60U+Qf9llAyaJEexQ==,type:str]
  HOMEPAGE_VAR_CF_KEY: ENC[AES256_GCM,data:ejamFarPRjtHC/ceBj3ykkFTsQdiexnlSPbSO0VVcU0skeO2Q9gBIQ==,iv:3ByZhweKPeHIngwYRWwR4vJXZG1SVa5lx0PIqGaxuLo=,tag:6ap1tEZOgMqgAGU4gVJHZg==,type:str]
  HOMEPAGE_VAR_TRAEFIK_USER: ENC[AES256_GCM,data:xBMvFEQ=,iv:OKfU4rCYfdRG1aIdgYTKqANtE2ICoNlKfejgjXPgLr0=,tag:O3E1wcPu3SI3+eoJslQcow==,type:str]
  HOMEPAGE_VAR_TRAEFIK_PASS: ENC[AES256_GCM,data:5nHbsIlCbuU=,iv:56HlDOB4BUQlyaRr6ZPV/OzVv2nRC0Xeg3uVJsMBNkM=,tag:KgvbUfWewlLiObuQKuLQ6g==,type:str]
  HOMEPAGE_VAR_UNIFI_USER: ENC[AES256_GCM,data:VgyuNthFYPuSLUuLanYc,iv:yxOVrlp2w3hl+HqWJqANNAg+VO2jjHtIJsSTLOjrhgY=,tag:YXq2Tfk4OaqDTwrvijcydQ==,type:str]
  HOMEPAGE_VAR_UNIFI_PASS: ENC[AES256_GCM,data:JAN5o5oVrM4=,iv:4wNNX7Sbmt162U5mA5VEYINUaHmGc0QaoiED7IZDhjo=,tag:M6JD/7m/b9C2zabjJkxWZg==,type:str]
  HOMEPAGE_VAR_WEATHER_KEY: ENC[AES256_GCM,data:E8M6RgxL5codCt7rQvq5FRxa8aoz8M75cwmT3t/6YdU=,iv:+QJpQpMLXnRNW7HmoiyCrB5SGHWZZphSy3KEJqUVbxo=,tag:eOPqXWxa41vt7PoRlV7WzQ==,type:str]
  HOMEPAGE_VAR_BAZARR_KEY: ENC[AES256_GCM,data:nbCznBdkQ4KPSd/yrO90LNiqYHASkHpy5CEYlUiJGLg=,iv:lzcDn9FtuUSFVuIIel/gy30uCaFrK4OWVNEENZZJo+8=,tag:+v2iwiuTb/PRssvD8mucog==,type:str]
sops:
  age:
    - recipient: age1v5nv69s859gf2494tevycyflcyezltjgvcss75ctgpdpv6wtu3fquywey3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieGtNN2tCRm9iSkNNbWFq
        UzJvWUJ2M3pTVzFMckl1cXVvbzJxRGNrVEZnCm9oZk1xaUVSV2pYaTBFSndpcUhz
        aUJKUVhDeUR0YURGckRTNXVweFZsajQKLS0tIGVXZEkyeTA1TGFvMnZiNU9iUERX
        c1FyT29WVWRMWFBuT1VMSUNLbkxBbGsKw53gsNUwUxmV1Wng6zf49c25lfJFmonx
        m9OWB/9+qlKHyU1vRz9oct+xNd/qfs3RqPe1aN7ILhFrW9bHYm21qw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T10:48:33Z"
  mac: ENC[AES256_GCM,data:pFARCxxvw+PC8DyY7Unjq2/A0I9Q4Mg6q7pUA2au6jQKfQlMH1K79W4lRMtn58o7yKTg9AyQ/ttl72a1VKsae3mj3WFg2uU89O1dXmVCFVnGAsOVYKFj5CphCmKHNvO6j7dyPNFaoFQs7f5DppBRJD2+naZl+N16zWxNb/2jAyI=,iv:7uGETFYapOYaF7TVoIM6VwjIu6GJ3gEvBaItlpGTDa4=,tag:mSUpjCff+eq5/cu1FozcaQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
