apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:v+Jw3uCEc5LDDQwd7MINXDKUUB++pQcbqj2iPnd6FV0=,iv:PnXgo2T03wGBC8ywlcuUiyuZYoa4/2BHAyiC3EXTuSg=,tag:MwvRl+h3DY/5nDzlxwn7wg==,type:str]
sops:
  age:
    - recipient: age1v5nv69s859gf2494tevycyflcyezltjgvcss75ctgpdpv6wtu3fquywey3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbHJTem9MVnYrVDl2NUh3
        NTE2aytGb0U2dHBkZGJhZWVWYXU4djBrTms0CkNEaUlyWS95aXRwQkdWSytJK2Ey
        c2FGdHRLOXRObzRleElmaGoxN3QyM0EKLS0tIGltdzRWR1BtOEdyaDBzOWZibVA1
        ZmltOURmVk9JdHVFNnN4VFQ4SnFqVHMKXpFVlbXJy6Yf4tkAigMJ75Tzku8FZ5E3
        Z2txHEbY9bGWlt/xi3HkZt8WPIczwKOGsFF6IOrSQvhMFsALDimk+g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T07:13:05Z"
  mac: ENC[AES256_GCM,data:5BUL6+wCesOkhfnLPxlvWQyy9ZLKtQ795daI84qIfAcdpJw6vmB6ItwmkDAz9jddTZNBXPWtU9pjodYCgfrghEDiq/pPNB2tJA5V+iurl6dE0znBa1D4rAykLXzYp0s5YOc+cQaYTRQravtCaLU75EQJVHxo1hGOaDuepS3Ixto=,iv:9n/842FnWpskPNbc63pDfKz5XV6EXn0cP561aEjtFwI=,tag:gbbyjfWWcdOtYVJ6fldErg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
