apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  postgres-password: ENC[AES256_GCM,data:HhugF6RXUb6x/matHeGDkm4F8wLO8/TV9HXuAhxOI+k=,iv:ftq/vJtQAbGh7D0/uxQWOTekeYF3ZSaBZCiOsipBYjY=,tag:zrfZWm4hdvuoWkHdyq91nA==,type:str]
  password: ENC[AES256_GCM,data:rp5Q6SKtehbr/ygxeOgne3GY6qxejcBEmBnAYF/hpYg=,iv:KYO3osVkf5RTd93GKbtKa1FC9i7iZV03x/Sfci9T+4E=,tag:jjQM3zIqSnlM5ofkBT5LZw==,type:str]
sops:
  age:
    - recipient: age1v5nv69s859gf2494tevycyflcyezltjgvcss75ctgpdpv6wtu3fquywey3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcmJjNTM4aS9pVWlrUm1N
        WkdPOGVLRHVvYVNDdDZhVVRjNU1ZMEUxKzBRCnQ3bElQODY4R1J0cEdrWGt4Zko2
        SEo3aVM1dnIvdm5jajRKbEZlSW45Z2sKLS0tIFN4SFo5Rk5Ecnh6WUc1NzJ1cy83
        VVQ5alREVXdCM2pTT2xnQmhJOVZaOHMKYFpTxy/s/fJQ624DFDW3Vc8kcy9vPzib
        Ok/9ip3t+i2qcpHInwAQzyh1DM9pOPaeLefrjiuY27OH1EDT0YA3lw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T07:07:10Z"
  mac: ENC[AES256_GCM,data:bGKDra4hMIC7T0sjrFaIaMWULpB2HfzdN+wKU3OpCmqNCmHSvuTSqidLCx8L5MN7f8GrjsOXb/UPiyPkbuMJnGw6XEvdCCBfZx7+bVW/NpgkXUKchOYhkNthW+d0BDJB3Y+xLFoCbJi8kNBHDTVkQ5aDFIHBrt67QjsF/KLAKmo=,iv:fo+0NUIAPGi5o6ICIRYgARPkFAS3WWyUDJRRYzARPCc=,tag:LrZflH4KtoqGtWfcAjHScQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
