---
name: Renovate

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: Dry run
        default: "false"
        required: false
      log_level:
        description: Log level
        default: debug
        required: false
  schedule:
    - cron: "0 * * * *" # Every hour
  push:
    branches: [main]
    paths:
      - .renovaterc.json5

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RENOVATE_PLATFORM: github
  RENOVATE_AUTODISCOVER: true
  RENOVATE_AUTODISCOVER_FILTER: "${{ github.repository }}"
  LOG_LEVEL: "${{ inputs.log_level || 'debug' }}"
  RENOVATE_DRY_RUN: "${{ inputs.dry_run || 'false' }}"

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: Run Renovate
        uses: renovatebot/github-action@v44.0.5
        with:
          configurationFile: .renovaterc.json5
          token: ${{ steps.app-token.outputs.token || secrets.GITHUB_TOKEN }}
